---
- name: Install programs on DevTools
  hosts: dev_tools
  become: yes
  # roles:
  #   - { role: geerlingguy.jenkins }

  tasks:

  - name: Install programs
    apt: 
      name: "{{packages}}"
    vars:
      packages:
      - openjdk-8-jdk
      - ansible
      - maven
      - git-core
      - wget

  - name: Add Jenkins apt repository key.
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      state: present

  - name: Add Jenkins apt repository.
    apt_repository:
      repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
      state: present
      # filename: jenkins
      update_cache: true

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
  - name: Allow port 8080
    shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
  - name: Start the server
    service:
      name: jenkins
      state: started
  # - wait_for:
  #     port: 8080
  #     command: cat /var/lib/jenkins/secrets/initialAdminPassword
  - name: Get Admin Password
    become: yes
    become_method: sudo
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
