---
- name: Variables Lesson
  hosts: all
  become: yes


  vars:
    message1: Privet
    message2: World
    secret  : XCXVXCXCXAVAVC

  tasks:

  - name: Print Secret variable
    debug:
      var: secret

  - debug: 
      msg: "Sekretnoe slovo: {{ secret }}"

  - debug:
      msg: "Owner of this server is {{ owner }}"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message
